version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: msia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/pg:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.4
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  application:
    build: .
    container_name: application
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
